import type { Metadata } from "next";
import "./globals.css";
import HeaderComponent from "@/components/header";
import FooterComponent from "@/components/footer";
import beni from "@/fonts/beni";
import roboto from "@/fonts/roboto";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${beni.variable} bg-black`}>
        <HeaderComponent />
        {children}
        <FooterComponent />
      </body>
    </html>
  );
}
